enum ZoneType {
  STATE,
  TOWN,
  LAKE,
  RIVER,
  OIL_SPILL,
  SWAMP,
  OCEAN,
  CREEK,
  POND,
  GLACIER,
  DISTRICT,
  TEXT_PRINTED,
  TEXT_WRITTEN,
}

const MapZones = [
  {
    ZoneTypeId: 0,
    ZoneTypeName: ZoneType.STATE,
    ZoneTypeNameHash: 0x77a848c7,
    ZoneName: 'Ambarino',
    ZoneNameHash: 0xf2d2e4a4,
  },
  {
    ZoneTypeId: 0,
    ZoneTypeName: ZoneType.STATE,
    ZoneTypeNameHash: 0x77a848c7,
    ZoneName: 'Guarma',
    ZoneNameHash: 0x7356b8ed,
  },
  {
    ZoneTypeId: 0,
    ZoneTypeName: ZoneType.STATE,
    ZoneTypeNameHash: 0x77a848c7,
    ZoneName: 'Lemoyne',
    ZoneNameHash: 0x00a55d60,
  },
  {
    ZoneTypeId: 0,
    ZoneTypeName: ZoneType.STATE,
    ZoneTypeNameHash: 0x77a848c7,
    ZoneName: 'LowerWestElizabeth',
    ZoneNameHash: 0x8a606f74,
  },
  {
    ZoneTypeId: 0,
    ZoneTypeName: ZoneType.STATE,
    ZoneTypeNameHash: 0x77a848c7,
    ZoneName: 'NewAustin',
    ZoneNameHash: 0x79e6a26b,
  },
  {
    ZoneTypeId: 0,
    ZoneTypeName: ZoneType.STATE,
    ZoneTypeNameHash: 0x77a848c7,
    ZoneName: 'NewHanover',
    ZoneNameHash: 0xb32957a3,
  },
  {
    ZoneTypeId: 0,
    ZoneTypeName: ZoneType.STATE,
    ZoneTypeNameHash: 0x77a848c7,
    ZoneName: 'NuevoParaiso',
    ZoneNameHash: 0x2496dfe4,
  },
  {
    ZoneTypeId: 0,
    ZoneTypeName: ZoneType.STATE,
    ZoneTypeNameHash: 0x77a848c7,
    ZoneName: 'UpperWestElizabeth',
    ZoneNameHash: 0xb5aa074d,
  },
  {
    ZoneTypeId: 0,
    ZoneTypeName: ZoneType.STATE,
    ZoneTypeNameHash: 0x77a848c7,
    ZoneName: 'WestElizabeth',
    ZoneNameHash: 0x4a4bfee7,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'AguasdulcesFarm',
    ZoneNameHash: 0x62a26859,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'AguasdulcesRuins',
    ZoneNameHash: 0x0bfd6f0a,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'AguasdulcesVilla',
    ZoneNameHash: 0xb80c99b7,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Annesburg',
    ZoneNameHash: 0x00704b67,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Armadillo',
    ZoneNameHash: 0xd39fe932,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'BeechersHope',
    ZoneNameHash: 0x9a2c155a,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Blackwater',
    ZoneNameHash: 0x3ec4b1f5,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Braithwaite',
    ZoneNameHash: 0x6a07dad2,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Butcher',
    ZoneNameHash: 0x8beccba3,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Caliga',
    ZoneNameHash: 0x6f0248be,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'cornwall',
    ZoneNameHash: 0x91a7512e,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Emerald',
    ZoneNameHash: 0xe3cdcf62,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'lagras',
    ZoneNameHash: 0x183ca5fa,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Manicato',
    ZoneNameHash: 0x4d704a4b,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Manzanita',
    ZoneNameHash: 0x57350b23,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Rhodes',
    ZoneNameHash: 0x79ff6291,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Siska',
    ZoneNameHash: 0x7ffe0593,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'StDenis',
    ZoneNameHash: 0xd25ec74f,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Strawberry',
    ZoneNameHash: 0x197dee02,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Tumbleweed',
    ZoneNameHash: 0xa51af855,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'valentine',
    ZoneNameHash: 0x1b6880b3,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'VANHORN',
    ZoneNameHash: 0x7ebd16bd,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'Wallace',
    ZoneNameHash: 0xcbfcd82e,
  },
  {
    ZoneTypeId: 1,
    ZoneTypeName: ZoneType.TOWN,
    ZoneTypeNameHash: 0x43dcbec5,
    ZoneName: 'wapiti',
    ZoneNameHash: 0x632572af,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_AURORA_BASIN',
    ZoneNameHash: 0xf446f723,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_BARROW_LAGOON',
    ZoneNameHash: 0x2f6910a6,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_CALMUT_RAVINE',
    ZoneNameHash: 0x0dc99072,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_ELYSIAN_POOL',
    ZoneNameHash: 0xf9b4b176,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_FLAT_IRON_LAKE',
    ZoneNameHash: 0xaf259737,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_HEARTLANDS_OVERFLOW',
    ZoneNameHash: 0x68a0d069,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_LAKE_DON_JULIO',
    ZoneNameHash: 0xae5a3e96,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_LAKE_ISABELLA',
    ZoneNameHash: 0x2350238d,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_O_CREAGHS_RUN',
    ZoneNameHash: 0x93a4fa9d,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_OWANJILA',
    ZoneNameHash: 0xb27bfcd7,
  },
  {
    ZoneTypeId: 2,
    ZoneTypeName: ZoneType.LAKE,
    ZoneTypeNameHash: 0xd829ad98,
    ZoneName: 'WATER_SEA_OF_CORONADO',
    ZoneNameHash: 0xf13a02fd,
  },
  {
    ZoneTypeId: 3,
    ZoneTypeName: ZoneType.RIVER,
    ZoneTypeNameHash: 0xba8b3109,
    ZoneName: 'WATER_ARROYO_DE_LA_VIBORA',
    ZoneNameHash: 0xfd09b97d,
  },
  {
    ZoneTypeId: 3,
    ZoneTypeName: ZoneType.RIVER,
    ZoneTypeNameHash: 0xba8b3109,
    ZoneName: 'WATER_BEARTOOTH_BECK',
    ZoneNameHash: 0x26c17d4b,
  },
  {
    ZoneTypeId: 3,
    ZoneTypeName: ZoneType.RIVER,
    ZoneTypeNameHash: 0xba8b3109,
    ZoneName: 'WATER_DAKOTA_RIVER',
    ZoneNameHash: 0x160ed9c7,
  },
  {
    ZoneTypeId: 3,
    ZoneTypeName: ZoneType.RIVER,
    ZoneTypeNameHash: 0xba8b3109,
    ZoneName: 'WATER_KAMASSA_RIVER',
    ZoneNameHash: 0xb6b5e477,
  },
  {
    ZoneTypeId: 3,
    ZoneTypeName: ZoneType.RIVER,
    ZoneTypeNameHash: 0xba8b3109,
    ZoneName: 'WATER_LANNAHECHEE_RIVER',
    ZoneNameHash: 0x865d425d,
  },
  {
    ZoneTypeId: 3,
    ZoneTypeName: ZoneType.RIVER,
    ZoneTypeNameHash: 0xba8b3109,
    ZoneName: 'WATER_LITTLE_CREEK_RIVER',
    ZoneNameHash: 0xabef3ddb,
  },
  {
    ZoneTypeId: 3,
    ZoneTypeName: ZoneType.RIVER,
    ZoneTypeNameHash: 0xba8b3109,
    ZoneName: 'WATER_LOWER_MONTANA_RIVER',
    ZoneNameHash: 0xb205f19c,
  },
  {
    ZoneTypeId: 3,
    ZoneTypeName: ZoneType.RIVER,
    ZoneTypeNameHash: 0xba8b3109,
    ZoneName: 'WATER_SAN_LUIS_RIVER',
    ZoneNameHash: 0xa65449e9,
  },
  {
    ZoneTypeId: 3,
    ZoneTypeName: ZoneType.RIVER,
    ZoneTypeNameHash: 0xba8b3109,
    ZoneName: 'WATER_UPPER_MONTANA_RIVER',
    ZoneNameHash: 0x95d61b35,
  },
  {
    ZoneTypeId: 5,
    ZoneTypeName: ZoneType.SWAMP,
    ZoneTypeNameHash: 0x12516aec,
    ZoneName: 'WATER_BAYOU_NWA',
    ZoneNameHash: 0xdec86bb3,
  },
  {
    ZoneTypeId: 6,
    ZoneTypeName: ZoneType.OCEAN,
    ZoneTypeNameHash: 0x7e8e05bf,
    ZoneName: 'WATER_BAHIA_DE_LA_PAZ',
    ZoneNameHash: 0xba5ab8e6,
  },
  {
    ZoneTypeId: 7,
    ZoneTypeName: ZoneType.CREEK,
    ZoneTypeNameHash: 0xdf7546a6,
    ZoneName: 'WATER_DEADBOOT_CREEK',
    ZoneNameHash: 0x4a3c149d,
  },
  {
    ZoneTypeId: 7,
    ZoneTypeName: ZoneType.CREEK,
    ZoneTypeNameHash: 0xdf7546a6,
    ZoneName: 'WATER_DEWBERRY_CREEK',
    ZoneNameHash: 0x1bf6cd08,
  },
  {
    ZoneTypeId: 7,
    ZoneTypeName: ZoneType.CREEK,
    ZoneTypeNameHash: 0xdf7546a6,
    ZoneName: 'WATER_HAWKS_EYE_CREEK',
    ZoneNameHash: 0xb3e8d688,
  },
  {
    ZoneTypeId: 7,
    ZoneTypeName: ZoneType.CREEK,
    ZoneTypeNameHash: 0xdf7546a6,
    ZoneName: 'WATER_RINGNECK_CREEK',
    ZoneNameHash: 0x778db1f6,
  },
  {
    ZoneTypeId: 7,
    ZoneTypeName: ZoneType.CREEK,
    ZoneTypeNameHash: 0xdf7546a6,
    ZoneName: 'WATER_SPIDER_GORGE',
    ZoneNameHash: 0xf2f73626,
  },
  {
    ZoneTypeId: 7,
    ZoneTypeName: ZoneType.CREEK,
    ZoneTypeNameHash: 0xdf7546a6,
    ZoneName: 'WATER_STILLWATER_CREEK',
    ZoneNameHash: 0xb3407c3f,
  },
  {
    ZoneTypeId: 7,
    ZoneTypeName: ZoneType.CREEK,
    ZoneTypeNameHash: 0xdf7546a6,
    ZoneName: 'WATER_WHINYARD_STRAIT',
    ZoneNameHash: 0xf069309e,
  },
  {
    ZoneTypeId: 8,
    ZoneTypeName: ZoneType.POND,
    ZoneTypeNameHash: 0xd22f5c53,
    ZoneName: 'WATER_CAIRN_LAKE',
    ZoneNameHash: 0xc0068eb7,
  },
  {
    ZoneTypeId: 8,
    ZoneTypeName: ZoneType.POND,
    ZoneTypeNameHash: 0xd22f5c53,
    ZoneName: 'WATER_CATTIAL_POND',
    ZoneNameHash: 0xd007a6a7,
  },
  {
    ZoneTypeId: 8,
    ZoneTypeName: ZoneType.POND,
    ZoneTypeNameHash: 0xd22f5c53,
    ZoneName: 'WATER_HOT_SPRINGS',
    ZoneNameHash: 0x460ea591,
  },
  {
    ZoneTypeId: 8,
    ZoneTypeName: ZoneType.POND,
    ZoneTypeNameHash: 0xd22f5c53,
    ZoneName: 'WATER_MATTLOCK_POND',
    ZoneNameHash: 0x11f25506,
  },
  {
    ZoneTypeId: 8,
    ZoneTypeName: ZoneType.POND,
    ZoneTypeNameHash: 0xd22f5c53,
    ZoneName: 'WATER_MOONSTONE_POND',
    ZoneNameHash: 0xcf9df96d,
  },
  {
    ZoneTypeId: 8,
    ZoneTypeName: ZoneType.POND,
    ZoneTypeNameHash: 0xd22f5c53,
    ZoneName: 'WATER_SOUTHFIELD_FLATS',
    ZoneNameHash: 0xcee7ed14,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'BayouNwa',
    ZoneNameHash: 0x78bfe1ac,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'bigvalley',
    ZoneNameHash: 0x3108c492,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'BluewaterMarsh',
    ZoneNameHash: 0x4dfa0b50,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'ChollaSprings',
    ZoneNameHash: 0xf9831c72,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'Cumberland',
    ZoneNameHash: 0x6d67801e,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'DiezCoronas',
    ZoneNameHash: 0x19700c95,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'GaptoothRidge',
    ZoneNameHash: 0x84d7ad0e,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'greatPlains',
    ZoneNameHash: 0x1c68ea97,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'GrizzliesEast',
    ZoneNameHash: 0xf8d68dc1,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'GrizzliesWest',
    ZoneNameHash: 0x62162401,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'GuarmaD',
    ZoneNameHash: 0xe1736cd7,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'Heartlands',
    ZoneNameHash: 0x07d4ff5f,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'HennigansStead',
    ZoneNameHash: 0x35390b10,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'Perdido',
    ZoneNameHash: 0xb1531168,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'PuntaOrgullo',
    ZoneNameHash: 0x56a7c746,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'RioBravo',
    ZoneNameHash: 0x8016c23f,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'roanoke',
    ZoneNameHash: 0x0aa5f25d,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'scarlettMeadows',
    ZoneNameHash: 0xcc7c3314,
  },
  {
    ZoneTypeId: 10,
    ZoneTypeName: ZoneType.DISTRICT,
    ZoneTypeNameHash: 0xdccaa2e0,
    ZoneName: 'TallTrees',
    ZoneNameHash: 0x6467ef09,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'p_2_bluewater_marsh',
    ZoneNameHash: 0x93334804,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_AURORA_BASIN',
    ZoneNameHash: 0x47192461,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_BAHIA_DE_LA_PAZ',
    ZoneNameHash: 0x9d32963d,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_BARROW_LAGOON',
    ZoneNameHash: 0x594d596c,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_CAIRN_LAKE',
    ZoneNameHash: 0x233dd2da,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_CATTAIL_POND',
    ZoneNameHash: 0x911b42fc,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_DAKOTA_RIVER',
    ZoneNameHash: 0xf7bc627c,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_DEADBOOT_CREEK',
    ZoneNameHash: 0x54898248,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_DEWBERRY_CREEK',
    ZoneNameHash: 0xf37cefea,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_ELYSIAN_POOL',
    ZoneNameHash: 0x6822c55d,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_ERIS_FIELD',
    ZoneNameHash: 0x478f80b5,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_FLAT_IRON_LAKE',
    ZoneNameHash: 0x00dbda50,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_HEARTLAND_OIL_FIELDS',
    ZoneNameHash: 0xc9c79854,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_HEARTLAND_OVERFLOW',
    ZoneNameHash: 0x7dc4a1c6,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_LAKAY',
    ZoneNameHash: 0x1bd5a429,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_LAKE_DON_JULIO',
    ZoneNameHash: 0x472f164a,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_LANNAHECHEE_RIVER',
    ZoneNameHash: 0x5ce61d88,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_LITTLE_CREEK_RIVER',
    ZoneNameHash: 0x780f20f9,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_LOWER_MONTANA_RIVER',
    ZoneNameHash: 0xc4270fe7,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_MATTOCK_POND',
    ZoneNameHash: 0x5d0900c3,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_MONTOS_REST',
    ZoneNameHash: 0xb6f67fd4,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_MOONSTONE_POND',
    ZoneNameHash: 0x63f6acb4,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_MOUNT_HAGEN',
    ZoneNameHash: 0x6ba71efc,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_OCREAGHS_RUN',
    ZoneNameHash: 0x2bd2b4e6,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_OWANJILA',
    ZoneNameHash: 0x5dcd45f1,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_ROANOKE_VALLEY',
    ZoneNameHash: 0x58db6580,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_SAN_LUIS_RIVER',
    ZoneNameHash: 0x678a6057,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_SEA_OF_CORONADO',
    ZoneNameHash: 0xe29827a8,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_SOUTHFIELD_FLATS',
    ZoneNameHash: 0xe78cb65f,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_SPIDER_GORGE',
    ZoneNameHash: 0x649e4cef,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_STILLWATER_CREEK',
    ZoneNameHash: 0xbd5364c5,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_UPPER_MONTANA_RIVER',
    ZoneNameHash: 0x4e98b0e9,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_3_WHINYARD_STRAIT',
    ZoneNameHash: 0x9640ba83,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_AGUASDULCES',
    ZoneNameHash: 0xb32bd1bd,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_ARMADILLO',
    ZoneNameHash: 0xe6eaeff7,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_ARROYO_DE_LA_VIBORA',
    ZoneNameHash: 0xcd5ce9a2,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_BACCHUS_BRIDGE',
    ZoneNameHash: 0x0c52c6a8,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_BACCHUS_STATION',
    ZoneNameHash: 0xcbf9c0af,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_BARDS_CROSSING',
    ZoneNameHash: 0x9cff54c5,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_BEARTOOTH_BECK',
    ZoneNameHash: 0xb76e9142,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_BENEDICT_PASS',
    ZoneNameHash: 0x57dbd9b8,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_BENEDICT_POINT',
    ZoneNameHash: 0xd3920730,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_BLACKWATER',
    ZoneNameHash: 0xc87d8b8a,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_BOLGER_GLADE',
    ZoneNameHash: 0xfbfee55c,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_BRAITHWAITE_MANOR',
    ZoneNameHash: 0xf60e3aed,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_CALIBANS_SEAT',
    ZoneNameHash: 0x222e5ced,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_CALIGA_HALL',
    ZoneNameHash: 0x7c43315a,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_CALUMET_RAVINE',
    ZoneNameHash: 0x192f0a3e,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_CINCO_TORRES',
    ZoneNameHash: 0x871db74e,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_CITADEL_ROCK',
    ZoneNameHash: 0xaf900bfb,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_COTORRA_SPRINGS',
    ZoneNameHash: 0xc69e4b94,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_CUMBERLAND_FALLS',
    ZoneNameHash: 0xe325c1f3,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_DIABLO_RIDGE',
    ZoneNameHash: 0x3db72923,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_DONNER_FALLS',
    ZoneNameHash: 0x7500a60f,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_EMERALD_RANCH',
    ZoneNameHash: 0x14de5ea9,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_FLATNECK_STATION',
    ZoneNameHash: 0xcd806933,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_FORT_MERCER',
    ZoneNameHash: 0xc22a2c44,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_FORT_WALLACE',
    ZoneNameHash: 0xfa0beea7,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_GRANITE_PASS',
    ZoneNameHash: 0xbd8b165e,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_HAWKS_EYE_CREEK',
    ZoneNameHash: 0xd5457035,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_JORGES_GAP',
    ZoneNameHash: 0x785538b2,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_KAMASSA_RIVER',
    ZoneNameHash: 0x5f15c77c,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_LA_CAPILLA',
    ZoneNameHash: 0x3ffc8a8f,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_LAGRAS',
    ZoneNameHash: 0x3552b0de,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_LAKE_ISABELLA',
    ZoneNameHash: 0x31941238,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_MACFARLANES_RANCH',
    ZoneNameHash: 0xa4a17fbd,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_MANTECA_FALLS',
    ZoneNameHash: 0xb84137a2,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_MANZANITA_POST',
    ZoneNameHash: 0x2279ee5f,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_MERCER_STATION',
    ZoneNameHash: 0xf6ad913c,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_MOUNT_SHANN',
    ZoneNameHash: 0x20b2d466,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_OWANJILA_DAM',
    ZoneNameHash: 0xab5763ff,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_PLAINVIEW',
    ZoneNameHash: 0x109b730c,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_QUAKERS_COVE',
    ZoneNameHash: 0x2af9f7c1,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_RATHSKELLER_FORK',
    ZoneNameHash: 0xcc796cbd,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_RHODES',
    ZoneNameHash: 0x4dd509f6,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_RIGGS_STATION',
    ZoneNameHash: 0x2ddede9f,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_RINGNECK_CREEK',
    ZoneNameHash: 0x695d3bfe,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_RIO_DEL_LOBO_ROCK',
    ZoneNameHash: 0x6ee4b99e,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_SAINT_DENIS',
    ZoneNameHash: 0x009ba3dc,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_SISIKA_PENITENTIARY',
    ZoneNameHash: 0x41f983c2,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_TEMPEST_RIM',
    ZoneNameHash: 0x867f0549,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_THIEVES_LANDING',
    ZoneNameHash: 0x35dce61e,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_THREE_SISTERS',
    ZoneNameHash: 0x8d2c1e7e,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_TUMBLEWEED',
    ZoneNameHash: 0x85d4c0d0,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_TWIN_ROCKS',
    ZoneNameHash: 0x89764f23,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_TWIN_STACK_PASS',
    ZoneNameHash: 0x3bd66c97,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_VALENTINE',
    ZoneNameHash: 0x960b8448,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_VAN_HORN_TRADING_POST',
    ZoneNameHash: 0x9e9e3406,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_WALLACE_STATION',
    ZoneNameHash: 0x56a56e44,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_4_WINDOW_ROCK',
    ZoneNameHash: 0x4a4c3f63,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_5_BRANDYWINE_DROP',
    ZoneNameHash: 0x40b8c6f2,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_5_EMERALD_STATION',
    ZoneNameHash: 0xb69452f7,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_5_STRAWBERRY',
    ZoneNameHash: 0xeb56f48b,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_5_WAPITI_INDIAN_RESERVATION',
    ZoneNameHash: 0xd423d45c,
  },
  {
    ZoneTypeId: 11,
    ZoneTypeName: ZoneType.TEXT_PRINTED,
    ZoneTypeNameHash: 0x9cb29bbb,
    ZoneName: 'P_6_ANNESBURG',
    ZoneNameHash: 0x88b34053,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_ABANDONED_MISSION',
    ZoneNameHash: 0xd1113443,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_ABANDONED_TRADING_POST',
    ZoneNameHash: 0x44ce7b03,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_ABERDEEN_PIG_FARM',
    ZoneNameHash: 0x0d0f2b79,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_ADLER_RANCH',
    ZoneNameHash: 0xc1cd737f,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_APPLESEED_TIMBER_COMPANY',
    ZoneNameHash: 0xe6f7dbf9,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_BAYGALL_EDGE',
    ZoneNameHash: 0x0be5c4cf,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_BEAR_CLAW',
    ZoneNameHash: 0xf035fc69,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_BEECHERS_HOPE',
    ZoneNameHash: 0x63f741e1,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_BRITTLEBRUSH_TRAWL',
    ZoneNameHash: 0xc9592823,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_BUTCHER_CREEK',
    ZoneNameHash: 0xe6a471eb,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CAIRN_LODGE',
    ZoneNameHash: 0x88ca196b,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CANEBREAK_MANOR',
    ZoneNameHash: 0x229d05ac,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CARMODY_DELL',
    ZoneNameHash: 0x8ea16502,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CASTORS_RIDGE',
    ZoneNameHash: 0xdb1a94c6,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CATFISH_JACKSONS',
    ZoneNameHash: 0x656fb687,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CENTRAL_UNION_RAILROAD_1',
    ZoneNameHash: 0x20144315,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CENTRAL_UNION_RAILROAD_2',
    ZoneNameHash: 0x5cdbbca3,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CENTRAL_UNION_RAILROAD_3',
    ZoneNameHash: 0x4a98181c,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CHEZ_PORTER',
    ZoneNameHash: 0x86be76ed,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CLAWSONS_REST',
    ZoneNameHash: 0x620d6f83,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CLEMENS_POINT',
    ZoneNameHash: 0x6d17ac2f,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CLINGMAN',
    ZoneNameHash: 0x767dc860,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_COCHINAY',
    ZoneNameHash: 0x1321e567,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_COLTER',
    ZoneNameHash: 0xa6cc7164,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_COMPSONS_STEAD',
    ZoneNameHash: 0x1f24b6ae,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_COOTS_CHAPEL',
    ZoneNameHash: 0xfc5a9494,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_COPPERHEAD_LANDING',
    ZoneNameHash: 0x40815011,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CORNWALL_KEROSENE_TAR',
    ZoneNameHash: 0x1d5bc2a5,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CRAWDAD_WILLIES',
    ZoneNameHash: 0xba9a795b,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_CUEVA_SECA',
    ZoneNameHash: 0x4a606200,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_DODDS_BLUFF',
    ZoneNameHash: 0x96933878,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_DORMIN_CREST',
    ZoneNameHash: 0xc88aa5e6,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_DOVERHILL',
    ZoneNameHash: 0xd98bb81d,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_DOWNES_RANCH',
    ZoneNameHash: 0xd8d62973,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_EL_NIDO',
    ZoneNameHash: 0x18e91d1b,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_EVELYN_MILLER_CAMP',
    ZoneNameHash: 0x3d67dd7c,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_EWING_BASIN',
    ZoneNameHash: 0xdf753206,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_FACE_ROCK',
    ZoneNameHash: 0x9372c764,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_FAIRVALE_SHANTY',
    ZoneNameHash: 0x9f50855a,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_FIRE_LOOKOUT_TOWER',
    ZoneNameHash: 0xd3a671fc,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_FIRWOOD_RISE',
    ZoneNameHash: 0xf7453243,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_FLATTENED_CABIN',
    ZoneNameHash: 0x565b032f,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_FORT_RIGGS_HOLDING_CAMP',
    ZoneNameHash: 0xce9ba997,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_GAPTOOTH_BREACH',
    ZoneNameHash: 0x026256ca,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_GILL_LANDING',
    ZoneNameHash: 0xff6dbcb4,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_GRANGERS_HOGGERY',
    ZoneNameHash: 0xcc18eff5,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_GREENHOLLOW',
    ZoneNameHash: 0x729c12af,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_GUTHRIE_FARM',
    ZoneNameHash: 0xa83d828c,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_HAGEN_ORCHARDS',
    ZoneNameHash: 0x01d5fac3,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_HANGING_DOG_RANCH',
    ZoneNameHash: 0xf9d63eb6,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_HANIS_BETHEL',
    ZoneNameHash: 0x2202ee4d,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_HILL_HAVEN_RANCH',
    ZoneNameHash: 0x96872368,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_HORSESHOE_OVERLOOK',
    ZoneNameHash: 0xaef74fb9,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_HOUSEBOAT',
    ZoneNameHash: 0x70f74b60,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_LAKE_DON_JULIO_HOUSE',
    ZoneNameHash: 0x9b1e5b7f,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_LARNED_SOD',
    ZoneNameHash: 0x695954da,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_LONE_MULE_STEAD',
    ZoneNameHash: 0xdd9efee5,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_LONNIES_SHACK',
    ZoneNameHash: 0x2df010e2,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_LUCKYS_CABIN',
    ZoneNameHash: 0x0dad94d2,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_MACLEANS_HOUSE',
    ZoneNameHash: 0xa11aedb9,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_MACOMBS_END',
    ZoneNameHash: 0x3f53bc77,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_MANITO_GLADE',
    ZoneNameHash: 0x55a6d12b,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_MARTHAS_SWAIN',
    ZoneNameHash: 0x300de595,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_MERKINS_WALLER',
    ZoneNameHash: 0x5082cf03,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_METEOR_HOUSE',
    ZoneNameHash: 0x8c3cd7f3,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_MICAHS_HIDEOUT',
    ZoneNameHash: 0x59d077ac,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_MILLESANI_CLAIM',
    ZoneNameHash: 0x7f1c3407,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_MOSSY_FLATS',
    ZoneNameHash: 0x3c93944a,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_NEKOTI_ROCK',
    ZoneNameHash: 0x1667c7a9,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_ODDFELLOWS_REST',
    ZoneNameHash: 0xda5fa6d8,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_OIL_DERRICK',
    ZoneNameHash: 0x4debb513,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_OLD_GREENBANK_MILL',
    ZoneNameHash: 0xeea64b2b,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_OLD_HARRY_FEN',
    ZoneNameHash: 0x5055b4e0,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_OLD_TOMS_BLIND',
    ZoneNameHash: 0x5f8e4341,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_OLD_TRAIL_RISE',
    ZoneNameHash: 0xf32cb01b,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_OSMAN_GROVE',
    ZoneNameHash: 0x15673770,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_PAINTED_SKY',
    ZoneNameHash: 0xa54b8915,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_PIKES_BASIN',
    ZoneNameHash: 0xebef68ee,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_PLANTERS_BAWN',
    ZoneNameHash: 0x9aaed2f4,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_PLEASANCE',
    ZoneNameHash: 0x353ac7bd,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_PLEASANCE_HOUSE',
    ZoneNameHash: 0x86b12d24,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_PRINZ_CO',
    ZoneNameHash: 0x6ee5c62b,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_PRONGHORN_RANCH',
    ZoneNameHash: 0xf8d01ece,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_RATTLESNAKE_HOLLOW',
    ZoneNameHash: 0x58105158,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_REPENTANCE',
    ZoneNameHash: 0x43bcb764,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_RIDGE_VIEW',
    ZoneNameHash: 0xd0ba4c63,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_RIDGEWOOD_FARM',
    ZoneNameHash: 0x5c0805ab,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_RILEYS_CHARGE',
    ZoneNameHash: 0x2c0b51ca,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_RIO_DEL_LOBO_HOUSE',
    ZoneNameHash: 0xb5a7caae,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_ROADSIDE_BROTHEL',
    ZoneNameHash: 0x664a6ef4,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_ROBARD_FARM',
    ZoneNameHash: 0x53800035,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_SAWBONE_CLEARING',
    ZoneNameHash: 0x3292e8d5,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_SCRATCHING_POST',
    ZoneNameHash: 0x005e5ceb,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_SHADY_BELLE',
    ZoneNameHash: 0x33a0d3ec,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_SHEPHERDS_RISE',
    ZoneNameHash: 0xe1f57d42,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_SILENT_STEAD',
    ZoneNameHash: 0xcc3a1981,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_SILTWATER_STRAND',
    ZoneNameHash: 0x377ab2f9,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_SIX_POINT_CABIN',
    ZoneNameHash: 0x7a9a9f57,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_SOLOMONS_FOLLY',
    ZoneNameHash: 0x345c766c,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_STILLWATER_CABIN',
    ZoneNameHash: 0x6f889f10,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_STILT_SHACK',
    ZoneNameHash: 0x4135dbbc,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_SWADBASS_POINT',
    ZoneNameHash: 0xbe7d779c,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_TANNERS_REACH',
    ZoneNameHash: 0xab5e835f,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_TAXIDERMIST_HOUSE',
    ZoneNameHash: 0x8f1bca55,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_THE_HANGING_ROCK',
    ZoneNameHash: 0x01ddd396,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_THE_LOFT',
    ZoneNameHash: 0xe5d84b79,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_THE_OLD_BACCHUS_PLACE',
    ZoneNameHash: 0xba0b2c82,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_TRADING_POST',
    ZoneNameHash: 0x845ced96,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_TRAPPERS_CABIN',
    ZoneNameHash: 0x163ae1e1,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_TWO_CROWS',
    ZoneNameHash: 0x80dc09ec,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_UTOPIAN_COLONY_BUILDING',
    ZoneNameHash: 0xd21ee891,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_VAN_HORN_MANSION',
    ZoneNameHash: 0x34863110,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_VENTERS_PLACE',
    ZoneNameHash: 0x0783569f,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_VETERANS_HOMESTEAD',
    ZoneNameHash: 0x3baf424f,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_WALLACE_OVERLOOK',
    ZoneNameHash: 0x65994796,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_WATSONS_CABIN',
    ZoneNameHash: 0xbac9b3a9,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_WILLARDS_REST',
    ZoneNameHash: 0xf6c518eb,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_4_WITCHES_CAULDRON',
    ZoneNameHash: 0x3375b1d2,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_ARGIL_RISE',
    ZoneNameHash: 0x0ea363c9,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_BEAVER_HOLLOW',
    ZoneNameHash: 0xf7b0eb8a,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_BERYLS_DREAM',
    ZoneNameHash: 0x4848054e,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_BLACK_BALSAM_RISE',
    ZoneNameHash: 0xc62ffbc6,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_BLACK_BONE_FOREST',
    ZoneNameHash: 0xa43c8951,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_BROKEN_TREE',
    ZoneNameHash: 0x81417da0,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_CHADWICK_FARM',
    ZoneNameHash: 0xcf732cfe,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_DEER_COTTAGE',
    ZoneNameHash: 0x298a013e,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_FISHINGSPOT',
    ZoneNameHash: 0x7c690b35,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_FORT_BRENNAND',
    ZoneNameHash: 0x97800bd2,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_GRAND_KORRIGAN_DOCKED',
    ZoneNameHash: 0x88cd8123,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_GRAND_KORRIGAN_SEA',
    ZoneNameHash: 0x603377b9,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_HURON_GLEN',
    ZoneNameHash: 0x0dc39324,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_LENORA_VIEW',
    ZoneNameHash: 0x3fe3547e,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_LIMPANY',
    ZoneNameHash: 0xce67af12,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_RADLEYS_PASTURE',
    ZoneNameHash: 0xf0840204,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_VALLEY_VIEW',
    ZoneNameHash: 0x292c5252,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_5_VETTERS_ECHO',
    ZoneNameHash: 0x5511f36c,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_6_RADLEYS_HOUSE',
    ZoneNameHash: 0x7678268d,
  },
  {
    ZoneTypeId: 12,
    ZoneTypeName: ZoneType.TEXT_WRITTEN,
    ZoneTypeNameHash: 0x886ad928,
    ZoneName: 'W_6_REED_COTTAGE',
    ZoneNameHash: 0x59607054,
  },
];

export default MapZones;
